### ISSUE TITLE
Some probe contours are wrong

### ISSUE THREAD

**Issue by alejoe91** [cambridge-neurotech/probe_maps#1]
Hi @WeissShahaf

I'm starting to build the probes and noticed that some of contours are wrong. Here is the list:
```
['ASSY-350-H12', 'ASSY-325-E-1', 'ASSY-236-H10', 'ASSY-276-H10', 'ASSY-350-H13', 'ASSY-196-H10b', 'ASSY-116-H10b', 'ASSY-350-H16', 'ASSY-325D-E-2', 'ASSY-37-H10b', 'ASSY-325D-E-1', 'ASSY-77-H10', 'ASSY-325-E-2', 'ASSY-325-H7', 'ASSY-156-H10', 'ASSY-158-H10']
```

and an example

<img width="659" height="588" alt="Image" src="https://github.com/user-attachments/assets/cb98ee3c-5e35-4268-82cf-fd49023e27cf" />

Can you check?

**Comment by cambridge-neurotech** [comment]
checking

**Comment by cambridge-neurotech** [comment]
should be fixed now

**Comment by alejoe91** [comment]
Still a couple are wrong:
```
['ASSY-350-H12', 'ASSY-350-H13']
```

**Comment by cambridge-neurotech** [comment]
fixed

**Comment by alejoe91** [comment]
They are still wrong, but almost fixed!

<img width="562" height="463" alt="Image" src="https://github.com/user-attachments/assets/13f5736f-5e61-4dc3-bd2a-748df8a589d7" />

<img width="562" height="463" alt="Image" src="https://github.com/user-attachments/assets/d8c26e46-7ca8-4167-b41d-dd3ace1ba9ea" />

**Comment by cambridge-neurotech** [comment]
<img width="1850" height="1050" alt="Image" src="https://github.com/user-attachments/assets/98bc6ffa-d2d3-4daf-90b3-2be0e3ac7c30" />
[ASSY-350-H13.json](https://github.com/user-attachments/files/24194897/ASSY-350-H13.json)

<img width="1850" height="1050" alt="Image" src="https://github.com/user-attachments/assets/54396219-c71d-4a50-a3e0-730a4eb66f10" />
[ASSY-350-H12.json](https://github.com/user-attachments/files/24194909/ASSY-350-H12.json)

**Comment by cambridge-neurotech** [comment]
try now
